 # Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x' 
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm install -g mbt @ui5/cli
  displayName: 'Install Cloud MTA Build Tool (MBT)'

- bash : |
    pip install shyaml
    cat mta.yaml | shyaml get-value description
    cat mta.yaml | shyaml get-value ID
    echo "##vso[task.setvariable variable=version;]$(cat mta.yaml | shyaml get-value version)"
    echo "##vso[task.setvariable variable=appName;]$(cat mta.yaml | shyaml get-value ID)"
    
  displayName: 'Get verison from yaml using shell'

- bash : |
    pip install shyaml
    echo "You can use macro syntax for variables: $(appName)"
    echo "Version is: $(version)"

- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/actions.sh'

- script: |
    ls
  displayName: 'List folder directory content pre-build'

- script: |
    mbt build -p=cf
  displayName: 'Build the MTA'

- script: |
    echo SAP App Version: $(version)
    cd mta_archives
    ls
    pwd
    cd ../
    pwd
    echo Pipeline.Workspace is : $(Pipeline.Workspace)
    echo Artificat Staging dir : $(Build.ArtifactStagingDirectory)
    echo Build Repo LocalPath :$(Build.Repository.LocalPath)
  displayName: 'List folder directory content post-build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.Repository.LocalPath)/mta_archives/sap-btp-sapui5_"$(version)".mtar'
    artifact: 'SAP-BTP-SAPUI5'
    publishLocation: 'pipeline'